### ISSUE TITLE
version increase when updating dependencies

### ISSUE THREAD

**Issue by zeevogels** [trailbehind/tilelive-gl#6]
You have updated dependencies without doing a version increase. Please consider increasing version when updating dependencies.

Because 'sharp' was upgraded to 0.22.0, it broke my app. Since it relies on Zlib 1.2.9 but the node:8 docker image sys Zlib is 1.2.8.

**Comment by JesseCrocker** [comment]
As this package is not published to NPM i don't really consider the version field relevant to anything, and I'm surprised that anyone else is using this. I'll bump the version number next time i make any changes, but you should really be pinning to a git commit, so that i don't have the ability to break your build by pushing a change.

**Comment by zeevogels** [comment]
Versions can be relevant outside of npm too, i guess.

Someone mentioned this here btw, https://github.com/mojodna/tessera/issues/88
I'm using it because mapbox deprecated their tilelive-gl years ago, and you're still updating :+1:
